baseURL = 'http://robsonfvlela.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'
contentDir = 'content'
enableEmoji = true
theme = 'hugo-theme-relearn'

[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'

#[module]
#    [[module.imports]]
#        path = "github.com/colinwilson/lotusdocs"
#        disable = false
#    [[module.imports]]
#        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
#        disable = false

[markup]
    [markup.tableOfContents]
      endLevel = 3
      startLevel = 1
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # https://jdhao.github.io/2019/12/29/hugo_html_not_shown/
  [markup.goldmark.parser]
    [markup.goldmark.parser.attribute]
      block = true

[languages]
  [languages.en]
    languageName = "English"
    title = "Robson"

    [languages.en.params]
      subtitle = "A simple, retro theme for Hugo"
      owner = ""
      keywords = ""
      copyright = ""
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      minuteReadingTime = "min read"
      words = "words"

      [languages.en.params.logo]
        logoText = "ã€‰ Robson"
        logoHomeLink = "/"

      [languages.en.menu]
        [[languages.en.menu.main]]
          identifier = "about"
          name = " About"
          url = "/about"  
      [[languages.en.menu.main]]
          identifier = "config"
          name = ".config"
          url = "/config"
#        [[languages.en.menu.main]]
#          identifier = "showcase"
#          name = "Showcase"
#          url = "/showcase"
        [[languages.en.menu.main]]
          identifier = "linux"
          name = "Linux"
          url = "/linux"
        [[languages.en.menu.main]]
          identifier = "macos"
          name = "MacOS"
          url = "/macos"
        [[languages.en.menu.main]]
          identifier = "terminal"
          name = "Terminal"
          url = "/terminal"
