baseURL = 'http://robsonfvilela.github.io/professor'
languageCode = 'en-us'
title = 'Prof. Robson'
contentDir = 'content'
enableEmoji = true
theme = 'hugo-theme-relearn'

[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'

#[module]
#    [[module.imports]]
#        path = "github.com/colinwilson/lotusdocs"
#        disable = false
#    [[module.imports]]
#        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
#        disable = false

[markup]
    [markup.tableOfContents]
      endLevel = 3
      startLevel = 1
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # https://jdhao.github.io/2019/12/29/hugo_html_not_shown/
  [markup.goldmark.parser]
    [markup.goldmark.parser.attribute]
      block = true

[languages]
  [languages.en]
    languageName = "English"
    title = "Prof. Robson"

    [languages.en.params]
      subtitle = "A simple, retro theme for Hugo"
      owner = ""
      keywords = ""
      copyright = ""
      menuMore = "Mostrar mais"
      readMore = "Leia mais"
      readOtherPosts = "Leita outras postagens"
      newerPosts = "Postagens novas"
      olderPosts = "Postagens velhas"
      missingContentMessage = "Página ..."
      missingBackButtonLabel = "Voltar ao início"
      minuteReadingTime = "min read"
      words = "words"

      [languages.en.params.logo]
        logoText = "〉 Robson"
        logoHomeLink = "/"

      [languages.en.menu]
        [[languages.en.menu.main]]
          identifier = "biografia"
          name = " Biografia"
          url = "/about"  
      [[languages.en.menu.main]]
          identifier = "config"
          name = ".config"
          url = "/config"
#        [[languages.en.menu.main]]
#          identifier = "showcase"
#          name = "Showcase"
#          url = "/showcase"
        [[languages.en.menu.main]]
          identifier = "linux"
          name = "Linux"
          url = "/linux"
        [[languages.en.menu.main]]
          identifier = "macos"
          name = "MacOS"
          url = "/macos"
        [[languages.en.menu.main]]
          identifier = "terminal"
          name = "Terminal"
          url = "/terminal"
